### ISSUE TITLE
Spaces are added at wrong places when typing in Sinhala in Emacs

### ISSUE THREAD

**Issue by lohang** [ibus/ibus-m17n#27] opened 2021-02-09 03:13 UTC
Hello, I am filing this here because I was suggested to file a bug for ibus in addition to Emacs. It appears that the problem occurs before the input reaches Emacs. (Please see here https://lists.gnu.org/archive/html/bug-gnu-emacs/2021-02/msg00391.html and here https://lists.gnu.org/archive/html/bug-gnu-emacs/2021-02/msg00413.html for background.)

**ISSUE**: When you type Sinhala with ibus m17n in Emacs, spaces get added at wrong places. Words get separated at wrong places as a result.

**How to reproduce:**

1) Open emacs 27.1 (the OS I use is Ubuntu 18.04. But I've been able to reproduce this on a couple of other OSs such as Fedora and Trisquel.)

2) Switch to Sinhala; Sinhalese Wijesekera (m17n). IBus version : 1.5.17

3) Type keys isxy, NdIdj.

4) Observe what happens when you hit space at the end of the first word.
And when you insert a space after full-stop.

Actual result : සිංහ ලභාෂාව .

Expected result : සිංහල භාෂාව.

This adds a space before the last character of the first word, not where
you want the space to be. Same happens when you enter a space after a
full-stop. It inserts the space BEFORE the full-stop.

**NOTE 1:** This is what it shows in my Emacs *Help* buffer when I enter 'C-h l':

 ස                      ;; org-self-insert-command
 ි                      ;; org-self-insert-command
 ං                      ;; org-self-insert-command
 හ                      ;; org-self-insert-command
 SPC                    ;; org-self-insert-command
 ල                      ;; org-self-insert-command
 භ                      ;; org-self-insert-command
 ා                      ;; org-self-insert-command
 ෂ                      ;; org-self-insert-command
 ා                      ;; org-self-insert-command
 ව                      ;; org-self-insert-command
 SPC                    ;; org-self-insert-command
 .                      ;; org-self-insert-command
 C-h l                  ;; view-lossage

**NOTE 2:** applications such as gedit, LibreOffice, Thunderbird do not have this issue.

**Comment by mike-fabian** [comment] 2021-10-13 10:08
What surprises me a bit is that you get a full stop at the end, because when I type a . using si-wijesekera (no matter whether with ibus-m17n or with ibus-typing-booster, I get ග. If I look into the file defining that input method, I see:

```
$ grep '"\."' /usr/share/m17n/si-wijesekera.mim 
  (",") ("<") (".") (">")
   ("." "ග")				; 0D9C
   ("'" ".")
   ("." "ග")				; 0D9C
   ("'" ".")
```
So it seems I have to type `'` to get a full stop.

I.e. typing

    `isxy, NdIdj'`

should give the result:

     සිංහල භාෂාව.

**Comment by mike-fabian** [comment] 2021-11-02 06:29
It turned out that this is not a bug in Emacs:

https://lists.gnu.org/archive/html/bug-gnu-emacs/2021-10/msg01126.html

**Comment by mike-fabian** [comment] 2021-11-02 06:32
It is a bug in XIM/ibus:

https://bugzilla.redhat.com/show_bug.cgi?id=2013610

**Comment by mike-fabian** [comment] 2022-09-19 16:00
https://bugzilla.redhat.com/show_bug.cgi?id=2013610 is still not fixed, but as this is not a but in ibus-m17n, I close the issue here.

**Closed by mike-fabian** 2022-09-19 16:00 UTC

**Comment by mike-fabian** [comment] 2023-03-06 11:17
```
ls /usr/share/m17n/si-*. mim
```

That shows you all m17n input methods for si (Sinhala) you can use with ibus-m17n or with ibus-typing-booster.

**Comment by aluyama** [comment] 2023-03-06 11:22
> ```
> ls /usr/share/m17n/si-*. mim
> ```
> 
> That shows you all m17n input methods for si (Sinhala) you can use with ibus-m17n or with ibus-typing-booster.

No, i mean in the codebase (this repository or other)

**Comment by mike-fabian** [comment] 2023-03-06 19:19
I don't understand the question. Can you please clarify it, be a bit more verbose?

**Comment by aluyama** [comment] 2023-03-09 08:14
> I don't understand the question. Can you please clarify it, be a bit more verbose?

Sorry, i'm not familiar with ibus project. Can you show me the source file of `wijesekara` layout. I couldn't find it.
Reason: I found that the "character binding" method (feature) does not work for some characters, so i want to identify the root case; or may be a font problem. i don't know yet.

**Comment by mike-fabian** [comment] 2023-03-09 09:25
The source file for the wijesekara layout is:

```
/usr/share/m17n/si-wijesekara.mim
```
It is written in a kind of lisp.

If you describe exactly what doesn't work right, I can help you improving it when I am back from vacation.

**Comment by mike-fabian** [comment] 2023-03-09 09:29
Upstream for this file is here:
https://git.savannah.nongnu.org/cgit/m17n/m17n-db.git/tree/MIM/si-wijesekera.mim

**Comment by aluyama** [comment] 2023-03-20 08:57
(a) @mike-fabian we are using an outdated version of wijesekara layout. (rev.2) this is the latest one (rev.3) https://www.language.lk/wp-content/uploads/2018/03/SLS-1134-2011.pdf
[SLS-1134-2011.pdf](https://github.com/ibus/ibus-m17n/files/11015150/SLS-1134-2011.pdf) (mirror)

(b)**layout name is incorrect,**
current name: wijesekera [ke]
correct name: wijesekara

> Upstream for this file is here: https://git.savannah.nongnu.org/cgit/m17n/m17n-db.git/tree/MIM/si-wijesekera.mim

it looks like the government hasn't provide source code for it. should i provide a code for this? i couldn't find the original submitter of rev.2 because upstream doesn't show the full history :(

**Comment by mike-fabian** [comment] 2023-03-20 09:08
It would be great if you can provide code.
I am still travelling until end of March, when I am back I can review your code. If you have problems, I can help after end of March.

**Comment by mike-fabian** [comment] 2023-04-03 13:20
I am back from vacation now. Did you work on updating the wijesekera layout? Do you need help?

**Comment by aluyama** [comment] 2023-04-23 03:56
@mike-fabian sorry for the delay. we celebrate the new year in april; i'll be back with an update soon.

**Comment by aluyama** [comment] 2024-07-13 01:47
> I am back from vacation now. Did you work on updating the wijesekera layout? Do you need help?

Done. https://git.savannah.nongnu.org/cgit/m17n/m17n-db.git/log/?h=wijesekara-SLS1134-2011

**Comment by aluyama** [comment] 2024-07-16 21:26
> I am back from vacation now. Did you work on updating the wijesekera layout? Do you need help?

@mike-fabian We are working on the upstream repository. We have sent a message to your email address (mfabian@redhat.com) and opened a separate thread https://lists.nongnu.org/archive/html/m17n-list/2024-07/msg00001.html

Can you help us?

**Comment by mike-fabian** [comment] 2024-07-17 09:52
> > I am back from vacation now. Did you work on updating the wijesekera layout? Do you need help?
> 
> @mike-fabian We are working on the upstream repository. The developer has opened a separate thread https://lists.nongnu.org/archive/html/m17n-list/2024-07/msg00001.html
> 
> Can you help us?

Thank you very much! I’ll make a new release of m17n-db very soon then!
