### ISSUE TITLE
Kannada kgp not working properly

### ISSUE THREAD

**Issue by GoutamHebbar** [ibus/ibus-m17n#7] opened 2018-11-23 18:20 UTC
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Ubuntu 18.04

Which desktop environment and version?: 
 GNOME 3.28.2

IBus version?: 
1.5.17

Issue description: Need to press every key twice to write kannada alphabets.

Steps to reproduce:
1. Change the keyboard language to kannada.(kgp m17n)
2. Start writing on notepad or in browser or anywhere.

Can you reproduce your problem with a new user account instead of the current your account?  no

Guys I don't have any knowledge about programming so I couldn't solve this issue on myself so I am asking here. Please help. There is no alternate keyboard app for kannada so it is really a problem when ibus is not working correctly. Thsi problem started to happen around a month back but before that it was very fine.
![screenshot from 2018-11-23 23-49-32](https://user-images.githubusercontent.com/45296204/48956708-8cad0d00-ef7a-11e8-9030-2fdc1ac9d37f.png)

**Comment by fujiwarat** [comment] 2018-11-26 06:35
I cannot reproduce this.
CC'ing @mike-fabian @pnemade

**Comment by pnemade** [comment] 2018-11-26 07:00
I don't have Ubuntu system but on Fedora 29 I tested this issue but I cannot reproduce the reported problem. I can use that keymap without any problem.

**Comment by mike-fabian** [comment] 2018-11-26 13:12
I cannot reproduce it on Fedora 29 either.

**Comment by mike-fabian** [comment] 2018-11-26 13:20
By the way, what happens if you use ibus-typing-booster to type Kannada using kgp?

Setup ibus-typing-booster like this to use kn-kgp:

![kn-kgp-used-in-ibus-typing-booster](https://user-images.githubusercontent.com/2330175/49016418-517f2980-f186-11e8-850a-5dd6db69212f.png)

**Comment by GoutamHebbar** [comment] 2018-11-26 13:38
@mike-fabian @pnemade @fujiwarat @phuang 
In my system previously it used to work fine but now I'm facing this problem. It might be possible that somehow my kgp keyboard got corrupted & so I'm having trouble in typing.

**Comment by GoutamHebbar** [comment] 2018-11-26 13:52
> By the way, what happens if you use ibus-typing-booster to type Kannada using kgp?
> 
> Setup ibus-typing-booster like this to use kn-kgp:
> 
> ![kn-kgp-used-in-ibus-typing-booster](https://user-images.githubusercontent.com/2330175/49016418-517f2980-f186-11e8-850a-5dd6db69212f.png)

I don't want any ibus suggestions because what I usually write doesn't include day to day words. also in indic language most words are formed after adding Swara to a consonant.

**Comment by mike-fabian** [comment] 2018-11-26 16:31
> @mike-fabian @pnemade @fujiwarat @phuang
> In my system previously it used to work fine but now I'm facing this problem. It might be possible that somehow my kgp keyboard got corrupted & so I'm having trouble in typing.
> Can I reinstall it by anyway?
> 
> To reproduce do this procedure
> 
>     1. Change the keyboard language to kannada.(kgp m17n)
> 
>     2. Start writing on notepad or in browser or anywhere.
> 
>     3. Just click 4-5 keys & then press space bar to indicate that the end of a word.
> 
>     4. Then press backspace & click Shift+M
> 
>     5. This should have produced a character similar to "o" but it will produce the character 'M'
> 
> 
> Step 4 alternate. Just press Shift+M after you changed the keyboard & refer to the next step.

This behaves as you describe, there is no difference
here between Ubuntu 18.04 and Fedora 29.

I don’t know whether this is a bug or a feature.

**Comment by mike-fabian** [comment] 2018-11-26 16:34
> > By the way, what happens if you use ibus-typing-booster to type Kannada using kgp?

> I don't want any ibus suggestions because what I usually write
> doesn't include day to day words. also in indic language most words
> are formed after adding Swara to a consonant the suggestions I'm
> seeing in the screenshot you have attached doesn't include them

ibus-typing-booster remembers what you type. I.e. it helps not only
for words which might be in a dictionary but also for words you type often.
The words you type often will appear in the suggestions with higher priority
than words from a dictionary.

**Comment by mike-fabian** [comment] 2018-11-26 16:40
> Issue description: Need to press every key twice to write kannada alphabets.

> ![screenshot from 2018-11-23 23-49-32](https://user-images.githubusercontent.com/45296204/48956708-8cad0d00-ef7a-11e8-9030-2fdc1ac9d37f.png)

Your screenshots seems to show the problem you described later,
i.e. the problem where typing Shift+M gives you an 'M' instead of
the character similar to 'o' you want.

But it doesn't seem to show that you need to press every key twice.

By the way, the behaviour when typing Shift+M is also the same when
using ibus-typing-booster, when typing it while the word is still in
preedit, the character similar to 'o' is added. When trying to add it
to a word already committed (i.e. a word where you already typed a
space after the end of the word) by going back to the end of that
word, Shift+M just inserts an 'M'.

So this behaviour does not seem to be Ubuntu specific.

**Comment by GoutamHebbar** [comment] 2018-11-26 17:10
> > Issue description: Need to press every key twice to write kannada alphabets.
> 
> > ![screenshot from 2018-11-23 23-49-32](https://user-images.githubusercontent.com/45296204/48956708-8cad0d00-ef7a-11e8-9030-2fdc1ac9d37f.png)
> 
> Your screenshots seems to show the problem you described later,
> i.e. the problem where typing Shift+M gives you an 'M' instead of
> the character similar to 'o' you want.
> 
> But it doesn't seem to show that you need to press every key twice.
> 
> By the way, the behaviour when typing Shift+M is also the same when
> using ibus-typing-booster, when typing it while the word is still in
> preedit, the character similar to 'o' is added. When trying to add it
> to a word already committed (i.e. a word where you already typed a
> space after the end of the word) by going back to the end of that
> word, Shift+M just inserts an 'M'.
> 
> So this behaviour does not seem to be Ubuntu specific.

The problem of pressing

**Comment by GoutamHebbar** [comment] 2018-11-26 17:11
@mike-fabian Something else click which I didn't suppose so in no way I want to close the thread.

**Comment by GoutamHebbar** [comment] 2018-11-26 17:12
@mike-fabian Something else click which I didn't suppose so in no way I want to close the thread.

**Comment by mike-fabian** [comment] 2018-12-05 15:55
Ping?

**Comment by mike-fabian** [comment] 2020-01-02 10:52
Closing because I cannot reproduce this.

**Closed by mike-fabian** 2020-01-02 10:52 UTC
