### ISSUE TITLE
Amharic input doesn't work on some apps 

### ISSUE THREAD

**Issue by elhananjair** [ibus/ibus-m17n#38] opened 2021-10-29 16:54 UTC
I am using Amharic - sera(m17n) as input method in IBus Preferences. Recently I am having a problem of typing with my native language (Amharic). I am using Fedora 34. 
It only working for me when I type in Onlyoffice, But on others apps like web browsers and text editors when I change the input method from English to Amharic, it still types in English. 
I don't know if this is the right repo to raise this issue. 

https://user-images.githubusercontent.com/69236638/139473461-29da11e1-d6e0-4d65-8c0b-a7b175dae488.mp4

**Comment by mike-fabian** [comment] 2022-01-18 08:57
It is the right repo to raise the issue. 

I cannot reproduce it though on Fedora 35 using XFCE.

Do you still have that problem?

What is your desktop environment? (I don’t recognize it from your video).

In Gnome Xorg on Fedora 35 it seems to work fine for me:


https://user-images.githubusercontent.com/2330175/149903991-ea76cbb5-8a1d-47ec-842c-754e73c94ca2.mp4

**Comment by mike-fabian** [comment] 2022-01-18 10:53
By the way, you can also use “Amharic - sera(m17n)” with ibus-typing-booster as shown in the following screenshot:

![Screenshot](https://user-images.githubusercontent.com/2330175/149923874-09f42ffb-4af0-4ccc-b8fa-e50f76b1ec07.png)

**Comment by mike-fabian** [comment] 2022-01-18 10:57
Using am-sera with ibus-typing-booster has the advantage that it also can do word completion and spellchecking.

Documentation of ibus-typing-booster is here: https://mike-fabian.github.io/ibus-typing-booster/

Even if you don’t need the extra features ibus-typing-booster has over ibus-m17n, it can still be a good idea to use ibus-typing-booster as it is more actively developed.

If you don’t want any of the extra features, you can disable them to emulated ibus-m17n as explained here:

https://mike-fabian.github.io/ibus-typing-booster/docs/user/#2_2_1_1

**Comment by elhananjair** [comment] 2022-01-19 09:59
> By the way, you can also use “Amharic - sera(m17n)” with ibus-typing-booster as shown in the following screenshot:
> 
> ![Screenshot](https://user-images.githubusercontent.com/2330175/149923874-09f42ffb-4af0-4ccc-b8fa-e50f76b1ec07.png)



> It is the right repo to raise the issue.
> 
> I cannot reproduce it though on Fedora 35 using XFCE.
> 
> Do you still have that problem?
> 
> What is your desktop environment? (I don’t recognize it from your video).
> 
> In Gnome Xorg on Fedora 35 it seems to work fine for me:
> Peek.2022-01-18.09-56.mp4

@mike-fabian thank you so much for your reply.
This issue still persists in some applications.
I am using Fedora 35 with the KDE Wayland Desktop environment.

https://user-images.githubusercontent.com/69236638/150107597-04e203aa-3963-40ed-b35a-5b69cc5ab558.mp4

**Comment by elhananjair** [comment] 2022-01-19 10:01
> Using am-sera with ibus-typing-booster has the advantage that it also can do word completion and spellchecking.
> 
> Documentation of ibus-typing-booster is here: https://mike-fabian.github.io/ibus-typing-booster/
> 
> Even if you don’t need the extra features ibus-typing-booster has over ibus-m17n, it can still be a good idea to use ibus-typing-booster as it is more actively developed.
> 
> If you don’t want any of the extra features, you can disable them to emulated ibus-m17n as explained here:
> 
> https://mike-fabian.github.io/ibus-typing-booster/docs/user/#2_2_1_1

Thanks a lot.
![image](https://user-images.githubusercontent.com/69236638/150107902-962ebdbf-8266-4aac-bb07-b906757d39a6.png)

I think I got this package installed but unfortunately, I haven't seen any word completion or spell checking until now, I don't if I have to configure something.

**Comment by juhp** [comment] 2022-01-20 08:49
Do you have imsettings-systemd installed?

**Comment by juhp** [comment] 2022-01-23 09:07
Could you try installing it then?

**Comment by elhananjair** [comment] 2022-01-23 10:28
I have installed that whats the purpose of this package though? 
and now ibus-typing-booster is working for me, I enabled it through ibus preferences -> input methods -> other - Typing Booster. After that, I have added the Amharic language from ibus-typing-booster settings and it suggests some words which very nice. 
But the main issue still persists, It works fine on firefox and some apps but it doesn't on others such as KWrite on KDE. 
Waterfox
![image](https://user-images.githubusercontent.com/69236638/150674258-bd4f7e1e-fee8-4cdc-822b-9bc08a603bca.png)

KWrite 
![image](https://user-images.githubusercontent.com/69236638/150674333-8a5bc7c7-d81e-4201-8cd4-14970d9572b3.png)

**Comment by mike-fabian** [comment] 2022-02-15 12:08
> But the main issue still persists, It works fine on firefox and some apps but it doesn't on others such as KWrite on KDE.

I guess this is because the environment variable QT_IM_MODULE is not set. The following environment variables  should be set to use ibus:

```
$ env | grep ibus
GTK_IM_MODULE=ibus
XMODIFIERS=@im=ibus
QT_IM_MODULE=ibus
mfabian@taka:~
$ 
```

**Comment by mike-fabian** [comment] 2022-02-15 13:05
> I have installed that whats the purpose of this package though?

The purpose of this package is to get you the environment variables which you need to use ibus set.

```
[mfabian@fedora ~]$ rpm -q imsettings-systemd
imsettings-systemd-1.8.3-1.fc35.x86_64
```

It creates these files:

```
[mfabian@fedora ~]$ ls .config/environment.d/
imsettings-gtk.conf  imsettings-qt.conf
[mfabian@fedora ~]$ cat .config/environment.d/imsettings-gtk.conf
GTK_IM_MODULE=ibus:xim
XMODIFIERS=@im=ibus
[mfabian@fedora ~]$ cat .config/environment.d/imsettings-qt.conf 
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
[mfabian@fedora ~]$
```

They are then used by systemd to set the variables in you environment.

To get systemd to pick that up, you need to reboot or

```
sudo systemctl daemon-reload
```

When you are logged in again to your KDE session, check whether the environment variables have been correctly set with `env | grep ibus` it should look like this:


```
$ env | grep ibus
GTK_IM_MODULE=ibus
XMODIFIERS=@im=ibus
QT_IM_MODULE=ibus
```

**Comment by mike-fabian** [comment] 2022-02-15 13:18
In this video one can see in the terminal that the environment variable QT_IM_MODULE=ibus is set.

I start kwrite and can type Amharic with typing booster.

Then I start kwrite again like this:

```
env -u QT_IM_MODULE kwrite &
```

i.e. I unset QT_IM_MODULE   for kwrite. Then  it does not work:

https://user-images.githubusercontent.com/2330175/154069510-f287053c-850b-4aff-a3c6-ebe70f40c408.mp4

**Comment by elhananjair** [comment] 2022-02-16 18:33
hey, @mike-fabian thank you for your reply, I stopped using ibus on Wayland and reverted to X11, now everything is working fine. I think the problem is with ibus on wayland.

**Comment by mike-fabian** [comment] 2022-02-17 08:31
Great to hear that it works for you now @elhananjair !

Indeed there are currently more problems using ibus in Wayland then in X11. I hope this situation will get be in future.

When testing KDE myself to investigate this issue here, I ran into a big problem on Plasma(X11) as well though and reported it here: https://bugzilla.redhat.com/show_bug.cgi?id=2054742

I am closing this issue here because in the end the problem turned out to be not related to ibus-m17n but rather to KDE/Wayland.

But if you have any issues with ibus-m17n or ibus-typing-booster using Amharic, please open new issues!

**Closed by mike-fabian** 2022-02-17 08:31 UTC
