### ISSUE TITLE
[BUG] Switching to a new input method fails in Ubuntu 22.10

### ISSUE THREAD

**Issue by O-Gopal** [ibus/ibus-m17n#56] opened 2022-12-24 04:10 UTC
With Ubuntu 22.10 (but not 22.04) with  ibus-m17n installed, switching to a different input method does nothing.

**To Reproduce**
1. Make sure my 2nd input method (in my case, "Sanskrit (sa-IAST (m17n))" appears under "Settings-->Keyboard-->Input sources."
2. Use alt-space to switch to my second input method.
3. Notice on the top panel that the indicator shows that the input method has changed.
4. Attempt to key in some special characters (using Gedit, LibreOffice, etc.).

**Expected behavior**
The special characters will appear.

**Actual behavior**
The keyboard behaves as if the input method were my usual "English (US)."

**ibus-m17n version?**
1-4.10-1

**m17n-db versions?**
1.8.0-3

**ibus version?**
1-5.27-2

**Distribution and version?**
Ubuntu 22.10

**Desktop and version?**
Gnome 3

**Xorg or Wayland?**
Wayland

**Additional context**
Removing and re-adding "Sanskrit (sa-IAST (m17n))" in Settings doesn't solve the issue.
Hardware: IBM ThinkPad Carbon X-1, 5th generation.
Reported on Launchpad: https://bugs.launchpad.net/ubuntu/+source/ibus-m17n/+bug/1993928

**Comment by mike-fabian** [comment] 2022-12-24 20:48
I think this is a duplicate of https://github.com/ibus/ibus-m17n/issues/52

This is the fix:

https://github.com/ibus/ibus-m17n/commit/b94603b6feb7696b9f43f0bea907e6acc63a13c7

The fix is included in ibus-m17n >= 1.4.17

Latest release: https://github.com/ibus/ibus-m17n/releases/tag/1.4.18

**Comment by mike-fabian** [comment] 2022-12-24 20:50
So either you can upgrade ibus-m17n to >= 1.4.17 or use the workaround described here:

https://github.com/ibus/ibus-m17n/issues/52#issuecomment-1249995669

Closing because this is fixed in the current release.

**Closed by mike-fabian** 2022-12-24 20:50 UTC
Labels: bug
