### ISSUE TITLE
Characters are swapping order when pressing space on Wayland

### ISSUE THREAD

**Issue by favadi** [ibus/ibus-m17n#19] opened 2020-02-24 13:55 UTC
I originally filed this bug against ibus (https://github.com/ibus/ibus/issues/2154), but further testing showed the problem doesn't happen with ibus-uinkey, so it should be ibus-m17n bug.

Which distribution and version?: 
Fedora 31

Which desktop environment and version?: 
GNOME 3.34.1

Which session type?: 
Wayland

Which application and version?: 
Tested with Firefox (firefox-70.0-1.fc31.x86_64) and Gedit (gedit-3.34.0-1.fc31.x86_64).

IBus version?: 
IBus 1.5.21 (ibus-1.5.21-3.fc31.x86_64)

Ibus m17n version?:

ibus-m17n-1.4.2-1.fc31.x86_64

Issue description:
Typing Vietnamese with Vietnamese (telex (m17n)), when pressing space, the order of previous input character is swap with the space itself. For example: tiếng<space> --> tiến<space>g 

See the attached video for visual explanation of the issue.
![Screencast-from-11-14-2019-08_28_46-AM](https://user-images.githubusercontent.com/782760/68819390-71bb3780-06ba-11ea-87fc-e6b96605128a.gif)

Steps to reproduce:
1.  typing a sentence in Vietnamese on Wayland

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

The problem doesn't happen on a X11 session.

**Comment by mike-fabian** [comment] 2020-06-20 14:54
Yes, this is a problem caused by wayland. Not all input methods are equally affected and some can work around it. It is a problem with forwarding key events.

I have no idea how to work around these wayland problems in ibus-m17n at the moment.

I suggest to use ibus-typing-booster instead.

You can also use the vi-telex input method in ibus-typing-booster.

ibus-typing-booster is more actively maintained the ibus-m17n and offers lots of extra features like completion which may be helpful.

Even  if you don’t need completions and just want the same behaviour as when using vi-telex with ibus-m17n, you can still use ibus-typing-booster as all the additional features can be switched off.

See this chapter in the documentation of ibus-typing-booster on how to switch off all the extra features to simulate the basic behaviour of ibus-m17n:

http://mike-fabian.github.io/ibus-typing-booster/documentation.html#simulate-ibus-m17n

Also, when using ibus-typing-booster on Wayland, you should use the option

“Use a workaround for a bug  in Qt im module”. That avoids a use of forward key events which
causes problems on Qt and Wayland. Using that option makes it work better on Wayland and some versions of Qt but makes it work worse on Xorg programs like xterm.

**Comment by mike-fabian** [comment] 2022-09-19 16:08
I cannot reproduce this problem on Gnome Wayland in Fedora 37 anymore:

https://user-images.githubusercontent.com/2330175/191062735-c737b6fe-78d5-49b7-acdb-a0d578448118.mp4

**Comment by mike-fabian** [comment] 2022-09-19 16:08
Maybe something has been fixed in Wayland.

And as this is not a problem in ibus-m17n, I am closing this issue here.

**Closed by mike-fabian** 2022-09-19 16:08 UTC
Labels: bug in other software

**Comment by mike-fabian** [comment] 2023-11-22 08:01
This bug is back, see https://github.com/ibus/ibus-m17n/issues/72 but it is a problem in Gnome or Mutter, not in ibus-m17n.
